### PR TITLE
NFS-2146: Weather icon is missing

### PR DESCRIPTION
**Pull request by Magnet-js**
### Type of Change

- [x] Bugfix
- [ ] Enhancement / new feature
- [ ] Refactoring
- [ ] Documentation
- [ ] Dependency

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [x] Review the [Contributing Guideline](https://github.com/Staffbase/custom-widgets-examples/blob/main/CONTRIBUTING.md) and sign CLA
- [ ] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Comment by Magnet-js** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by maximizeIT** [comment]
@Magnet-js @m-seidel can we merge this PR? :)

**Comment by m-seidel** [comment]
> @Magnet-js @m-seidel can we merge this PR? :)

Nope it needs a bit more work

**Comment by Ninerian** [comment]
Replaced by #81

**Pull request closed without merging**
